data:
  dataset: MBS
  k_cutoff: 6
  top_genes: 3000
mode: clustering
model:
  pos_knn: 8
  pos_sigma: 1
  dic_hidden: 64
train:
  decay: 0.0001
  epochs: 500
  lr: 0.001
  t_step: 100
  w_mean: 1
  w_recon: 1.5
  w_tri: 0.05
  w_adj: 0.1
  adj_start_epoch: 100
  adj_warmup_epochs: 100
